[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  esp32async/ESPAsyncWebServer
  esp32async/AsyncTCP
  hideakitai/ESP32SPISlave
  knolleary/PubSubClient

build_flags =
  -DCORE_DEBUG_LEVEL=3
